### ISSUE TITLE
Unable to clear description field on issues.

### ISSUE THREAD

**Issue by pbendersky** [NARKOZ/gitlab#110]
When calling:
```
          Gitlab.edit_issue(project_id, issue_id, {
            description: "",
          })
```

the issue's description is not updated.

**Comment by asedge** [comment]
Something in the Gitlab API code must be preventing this because we just pass the options hash along to the endpoint.

I think I found it: https://github.com/gitlabhq/gitlabhq/blob/master/lib/api/helpers.rb#L126.  

If I change `if params[key].present?` to `if params[key]` I can pass in an empty string via the API and the description get cleared. I would recommend creating an issue with the GitlabHQ project.

**Comment by pbendersky** [comment]
Thank you. Just reported it on GitLab. (https://github.com/gitlabhq/gitlabhq/issues/8832 for reference).
