### ISSUE TITLE
Get result of CLI request in JSON

### ISSUE THREAD

**Issue by michaellihs** [NARKOZ/gitlab#140]
Thanks a lot for this great library - I recently use the CLI tool a lot and it's a big help in my daily work with Gitlab.

My question: is there any chance to get the output of the commands in a JSON-format instead of the 'table format'?

E.g. instead of
````
+-------------+-----+-------------+------------+
| Gitlab.create_group Test Gruppe, test_group  |
+-------------+-----+-------------+------------+
| description | id  | name        | path       |
+-------------+-----+-------------+------------+
|             | 107 | Test Gruppe | test_group |
+-------------+-----+-------------+------------+
````

something like

````
{
  "command" : "Gitlab.create_group Test Gruppe, test_group",
  "result" : {
    "description" : "",
    "id" : "107",
    "name" :  "Test Gruppe",
    "path" : "test_group"
  }
}
````

with this feature, it would be possible to pipe the result into other commands using tools like [jq](http://stedolan.github.io/jq/).

If you'd provide me a hint on where to get started, I'd also try to add this feature myself and create a pull request.

Thanks a lot!

**Comment by NARKOZ** [comment]
Good idea! :+1:

We use [`Gitlab::CLI.run`](https://github.com/NARKOZ/gitlab/blob/65f485d9ec22ce884c368ba0e46fc68e4ebc7b30/lib/gitlab/cli.rb#L30) to process a CLI command. 
Then we format output with [`output_table`](https://github.com/NARKOZ/gitlab/blob/65f485d9ec22ce884c368ba0e46fc68e4ebc7b30/lib/gitlab/cli_helpers.rb#L90-L100) method.

We probably need to add a special argument `--json` that will output result as a JSON instead of table.

**Comment by michaellihs** [comment]
Would be great to get some feedback on this one

https://github.com/NARKOZ/gitlab/pull/142

btw: it's my first pull request ever and I am a Ruby newb... so please be kind :-)

**Comment by michaellihs** [comment]
@NARKOZ - any news about my Pull Request?

**Comment by peterkraume** [comment]
+1 for this feature request!

**Comment by thomasdarimont** [comment]
+1 this would be super useful!

**Comment by asedge** [comment]
@michaellihs Thanks, your code has been merged!
