### ISSUE TITLE
auto_paginate fails when using https instead of http

### ISSUE THREAD

**Issue by iv-mexx** [NARKOZ/gitlab#179]
I've encountered a strange problem when changing the url to my gitlab instance from http to https.
When using https, `auto_paginate` does not work correctly anymore: It reports that the server responds with `401 - Unauthorized`, but everything works find when using http:

```ruby
[8] pry(Fastlane::Actions::GitlabGetProjectsAction)> c
=> #<Gitlab::Client:0x007fbfad00dee8 @endpoint="https://git.mygitlab.at/api/v3", @httparty={:verify=>false}, @private_token="mytoken", @user_agent="Gitlab Ruby Gem 3.6.1">
[9] pry(Fastlane::Actions::GitlabGetProjectsAction)> c.projects.count
=> 20
[10] pry(Fastlane::Actions::GitlabGetProjectsAction)> c.projects.auto_paginate.count
Gitlab::Error::Unauthorized: Server responded with code 401, message: You need to sign in or sign up before continuing.. Request URI: https://git.mygitlab.at/api/v3http://git.mygitlab.at/api/v3/projects?page=2&per_page=20
from /Users/mexx/.rvm/gems/ruby-2.2.2/gems/gitlab-3.6.1/lib/gitlab/request.rb:69:in `validate'
```

Interestingly, the Request URI is reported to be `https://git.mygitlab.at/api/v3http://git.mygitlab.at/api/v3/projects?page=2&per_page=20`, so first its the endpoint url WITH https, then its the actual endpoint url WITHOUT https. 

Also note that I have another gitlab instance (I'm working on a tool to migrate gitlab projects from one private instance to another private instance) where the https url works without a problem!

**Comment by NARKOZ** [comment]
We use [link headers](https://github.com/gitlabhq/gitlabhq/tree/master/doc/api#pagination-link-header) for pagination. Are you sure that your server returns correct headers in response?

**Comment by asedge** [comment]
I just tried exactly what you did on my HTTPS enabled Gitlab instance and `auto_paginate` works as expected.  I got 20 projects without and 207 with using it.  I think @NARKOZ is correct, your Gitlab instance may not be returning the correct headers in the response.

[This](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/paginated_response.rb#L83-L84) strips out the `endpoint` from the `next` link header but since they don't match you end up with the mangled URL you got.

Since there's been no response in a while I'm closing this.  Reopen if you need further help.

**Comment by iv-mexx** [comment]
Sorry for not responding.
I was looking into this just now again: We had a redirect from `http://git.mygitlab.com` to `https://git.mygitlab.com` which seems to be the problem somehow. After I've deactivated this redirect, it was working...
