### ISSUE TITLE
Update JSON gem 

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#217]
As mentioned in https://github.com/danger/danger/issues/521 could we update the gem to use JSON 2.x? Or even just drop the dependency entirely since most functionality is built into Ruby nowadays.

**Comment by k0nserv** [comment]
To my understanding that gem is only being included for Ruby versions less than 2.0 per https://github.com/NARKOZ/gitlab/blob/master/gitlab.gemspec#L22-L24 It's included via HTTParty

**Comment by connorshea** [comment]
Ah, I guess it would be worth considering dropping support for anything less than Ruby 2.1 in that case. But this isn't the issue to discuss that in :) Closing.

**Comment by orta** [comment]
This isn't strictly true - just checked, as with CocoaPods, Rubygems parses the ruby file and then submits that up to the Gem server as a compiled JSON package: https://rubygems.org/api/v1/gems/gitlab.json

As this gem was submitted with a 1.9 version of ruby, then everyone who uses Rubygems from the main API gets HTTParty 0.13

```json
"runtime": [
  {
    "name": "httparty",
    "requirements": "~> 0.13.0"
  },
  {
    "name": "terminal-table",
    "requirements": ">= 0"
  }
]
```

In theory [this line in the Gemspec](https://github.com/NARKOZ/gitlab/blob/master/gitlab.gemspec#L22) would need to be 

```ruby
  if RUBY_VERSION < '2.0' && ENV['TESTING']
```

Or something similar, to ensure the tests still pass, as that's why it was added: https://github.com/NARKOZ/gitlab/commit/268a19b7d4f92a66fd17e50e09b73601abdb20c0

**Comment by asedge** [comment]
@dblessing and @jvanbaarsen -  Wanted to see if you had any feedback on dropping support for Ruby 1.9.3 for version 4.0.

**Comment by connorshea** [comment]
@asedge I don't have any problem with it, the GitLab app doesn't support 1.9.3 and the most major project (that I know of) dependent on this gem is Danger, which doesn't support 1.9.3 either.

**Comment by jvanbaarsen** [comment]
@asedge Let's do this :-)

**Comment by connorshea** [comment]
This can be closed now :)
