### ISSUE TITLE
httparty 0.14.0

### ISSUE THREAD

**Issue by liger1978** [NARKOZ/gitlab#246]
httparty 0.14.0 is out.  If it works OK with the gitlab gem we should update our dependencies accordingly.

**Comment by liger1978** [comment]
Ah, this has already been changed.  When will there be a new release?

**Comment by kvokka** [comment]
With it will be easy to invoke TLS support by httparty (Now I'm waiting when [PR](https://github.com/jnunemaker/httparty/pull/499) will be accepted)

**Comment by asedge** [comment]
@liger1978 Unknown.  Still considering the options of how to handle v3 vs v4 API changes that will exist in Gitlab 9 (https://github.com/NARKOZ/gitlab/issues/241).  Trying to hold off doing a major release until a path forward is in place or at least there's a good approach.

**Comment by liger1978** [comment]
Fair enough.  How about a 3.7.1 release? :wink:

**Comment by asedge** [comment]
I don't think we want to drop support for Ruby < 2.0 in a bugfix release.  You could always clone this git repo, bump the `Gitlab::VERSION` and build the gem locally.  Alternatively, [bundler lets you declare gem dependencies from github](http://bundler.io/git.html).

**Comment by akerl** [comment]
Not bumping the Ruby version dep in a bugfix release makes sense, but does it not then make sense to bump the major? Ruby 2.4.0 ships json-2.0.2 as a default built-in, so the published gitlab gem fails to work at all when combined with code that imports json.

**Comment by asedge** [comment]
@akerl It does.  I wanted to wait to do a major release until there at least is a plan for v3/v4 API routing differences.  I proposed an idea in #241.  I don't like the implementation I suggested and haven't come up with something better.  Since Gitlab 9 should be released *soon* I was also hoping to just drop support for Gitlab API v3 in this gem's 4.0.0 release.  Dropping support for v3 of the Gitlab API also seemed worthy of a major release bump.  It also seemed convenient to have the major version of this gem track the latest API version supported, hence why I've been stalling.

If you want to help with #241 or have a suggestion on how we could accomplish supporting both v3 and v4 I'm willing to collaborate.  My time, unfortunately, is limited - which is another reason no progress has been made.
