### ISSUE TITLE
request to get raw file is not working for filename having dot

### ISSUE THREAD

**Issue by raviiitb** [NARKOZ/gitlab#269]
Request to get raw file is not working when there is dot in filename.
Eg-
**Filename without dot-** Working fine
https://gitlab.com/api/v3/projects/3045354/repository/files/Gemfile/raw?ref=master

**Filename with dot-** Throwing error `{"message":"404 File Not Found"}`
https://gitlab.com/api/v3/projects/3045354/repository/files/Gemfile.lock/raw?ref=master
_Encoded form-_
https://gitlab.com/api/v3/projects/3045354/repository/files/Gemfile%2Elock/raw?ref=master

**Comment by asedge** [comment]
I apologize for not having read through this better.  You may be looking to file a bug against `GitlabHQ` not the `Gitlab` ruby gem that wraps the Gitlab API

**Comment by cvand** [comment]
I believe this is a bug in the gem. In fact in client.rb you have:
def url_encode(s)
    ERB::Util.url_encode(s)
end

and erb Util won't convert the dot into %2E, but URI.encode(s, /\W/) will.

If you try to call file_contents with an already encoded string it'll double encode it so that won't work either.

I will be submitting a PR for this fix.

**Comment by raviiitb** [comment]
It seems its fixed now. File name with `dot(.)` working fine now
