### ISSUE TITLE
Wrong path for MR endpoint

### ISSUE THREAD

**Issue by reshadf** [NARKOZ/gitlab#494]
### Summary

When using the Ruby Wrapper for the GITLAB REST API, fetching the MR discussions fails. This is probably because the Request URI is not correct. ( see below )

### Steps to reproduce

within Danger ( danger.systems )

call the following API 
`client.merge_request_discussions(ci_source.repo_slug, ci_source.pull_request_id).auto_paginate`

### What is the current *bug* behavior?

(What actually happens)
The current output is generated because the call fails due to the URL not being correct in the Ruby Gems API Wrapper (v4.11.0) : 
```
Gitlab::Error::NotFound: Server responded with code 404, message: 404 API Version Not Found. Request URI: https://gitlab.intern.mydomain.com/api/v4http://gitlab.intern.mydomain.com/api/v4/projects/26/merge_requests/443/discussions?id=26¬eable_id=443&page=2&per_page=20
  /usr/share/rvm/gems/ruby-2.6.2/gems/gitlab-4.11.0/lib/gitlab/request.rb:67:in `validate'
  /usr/share/rvm/gems/ruby-2.6.2/gems/gitlab-4.11.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
  /usr/share/rvm/gems/ruby-2.6.2/gems/gitlab-4.11.0/lib/gitlab/paginated_response.rb:92:in `next_page'
  /usr/share/rvm/gems/ruby-2.6.2/gems/gitlab-4.11.0/lib/gitlab/paginated_response.rb:40:in `each_page'
  /usr/share/rvm/gems/ruby-2.6.2/gems/gitlab-4.11.0/lib/gitlab/paginated_response.rb:47:in `auto_paginate'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/lib/danger/request_sources/gitlab.rb:78:in `mr_comments'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/lib/danger/request_sources/gitlab.rb:172:in `update_pull_request_with_inline_comments!'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/lib/danger/request_sources/gitlab.rb:165:in `update_pull_request!'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/lib/danger/danger_core/dangerfile.rb:278:in `run'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/lib/danger/danger_core/executor.rb:29:in `run'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/lib/danger/commands/runner.rb:72:in `run'
  /usr/share/rvm/gems/ruby-2.6.2/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/share/rvm/gems/ruby-2.6.2/gems/danger-6.0.6/bin/danger:5:in `<top (required)>'
  /usr/share/rvm/gems/ruby-2.6.2/bin/danger:23:in `load'
  /usr/share/rvm/gems/ruby-2.6.2/bin/danger:23:in `<top (required)>'
```

### What is the expected *correct* behavior?

I think the URL generated by the API wrapper should be correct

see https://github.com/danger/danger/issues/1124 I think the actual problem is in this library though

**Comment by NARKOZ** [comment]
How do you set gitlab API endpoint?

**Comment by reshadf** [comment]
I have/had in my Gitlab Variables the following: `DANGER_GITLAB_API_BASE_URL = https://gitlab.intern.mydomain.com/api/v4`

After removing this one and adding the endpoint with `GITLAB_API_ENDPOINT` it seems to be working partially?

**Comment by Quantu** [comment]
I also experienced this issue after one of the more recent gitlab server updates, and it is limited to auto_paginate. The request api path (https://gitlab.intern.mydomain.com/api/v4 in this case) doesn't match the api path in the return (http://gitlab.intern.mydomain.com/api/v4 - not https like the request). Since the substitutions in paginated_response.rb (lines 67, 79, 91, 103) don't match, so you end up with a messed up request URI like this: https://gitlab.intern.mydomain.com/api/v4http://gitlab.intern.mydomain.com/api/v4/projects/26/merge_requests/443/discussions?id=26¬eable_id=443&page=2&per_page=20

This also happens if you try to access it via IP, which is what I want to do. The server now seems to return the URI based on it's configured name, not the URI by which it was accessed. I access at http://127.0.0.1/api/v4, but get a return with my server's hostname over SSL (e.g. https://example.gitlab.com/api/v4). I temporarily worked around the issue by hardcoding the substitutions in paginated_response.rb, but it would be nice to have a permanent fix.

**Comment by reshadf** [comment]
After some debugging and thanks to @Quantu, I found out that in our GITLAB config the following line was pointed to HTTP instead of https ( while we used https ) 

# note the 'https' below
external_url "https://gitlab.example.com"

That was the reason we got a messed up URL. Changing it to https fixed it for us. 

See https://docs.gitlab.com/omnibus/settings/nginx.html

Unfortunately, my Ruby skills are not that great so I couldn't create a PR to take this into account when other people misconfigured this but hopefully, someone else can with this knowledge.
