### ISSUE TITLE
gitlab help jobs displays an invalid syntax

### ISSUE THREAD

**Issue by perlun** [NARKOZ/gitlab#599]
Hi,

Thanks for a nice gem. I discovered a slight issue now with the JSON-parameter displayed in the `gitlab jobs` example below:

```
$ gitlab help jobs
= Gitlab::Client::Jobs.jobs
(from gem gitlab-4.16.1)
=== Implementation from Jobs
------------------------------------------------------------------------------
  jobs project_id options = {}
------------------------------------------------------------------------------
Gets a list of Jobs for a Project
@example
  gitlab jobs 1
  gitlab jobs "project"
  gitlab jobs "project" "{scope: ["manual" "success"] per_page: 100 }"
@param  [Integer String] id The ID or name of a project.
@param  [Hash]
options A customizable set of options.
@option options [Array] :scope The scope of jobs to show one or array of: created pending running failed success canceled skipped manual; showing all jobs if none provided.
@option
options [Integer] :page The page number.
@option options [Integer] :per_page The number of results per page.
@return [Array<Gitlab::ObjectifiedHash>]
```

The problem is that `gitlab jobs "project" "{scope: ["manual" "success"] per_page: 100 }"` is not a valid syntax. Executing this gives me `Error: Argument is not valid YAML syntax: {scope: [manual success] per_page: 100 }`.

The correct example would be this: `gitlab jobs "project" "{scope: ["manual", "success"], per_page: 100 }"`.

I'd happily submit a fix, but AFAICT, this is generated based on https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/jobs.rb, and the commas are presumably stripped there somewhere, so it seems tricky. Any ideas? (feel free to fix it yourself if it's easier to fix than explaining how to fix it. :laughing:)

**Comment by desnudopenguino** [comment]
it appears to be correct in the actual formatting of the ri file. in my case, under the @example section, i only see 3 lines with `gitlab jobs` and nothing beyond that. i cd'd into the docs dir for the gem and ran `ri -T jobs` and got the appropriate output though. i wouldn't think it a SHELL or TERM issue since the command shows the correct output, but something is getting lost somewhere.

i'm using:
ri 6.2.1
ruby 2.7.1
gitlab ruby gem 4.17.0

on OpenBSD 6.8
